appdevforall/CodeOnTheGo

- app/build.gradle.kts
- app/src/androidTest/kotlin/com/itsaky/androidide/WelcomeScreenTest.kt
- app/src/androidTest/kotlin/com/itsaky/androidide/screens/OnboardingScreen.kt
- gradle/libs.versions.toml
- settings.gradle.kts
Add the Kaspresso test for the Welcome screen.
https://appdevforall.atlassian.net/browse/ADFA-319
> ADFA-319 - Welcome Screen Test

- app/src/androidTest/kotlin/com/itsaky/androidide/PermissionsScreenTest.kt
- app/src/androidTest/kotlin/com/itsaky/androidide/screens/PermissionScreen.kt
- app/src/androidTest/kotlin/com/itsaky/androidide/screens/SystemPermissionsScreen.kt
Add the Kaspresso test for the Permissons screen.
https://appdevforall.atlassian.net/browse/ADFA-320
> [ADFA-320] - add Permissions Screen Test

- libs_source/bootstrap/bootstrap-aarch64.zip
- libs_source/bootstrap/bootstrap-arm.zip
- libs_source/bootstrap/bootstrap-x86_64.zip
- termux/termux-app/src/main/assets/data/common/idesetup.sh
Fix for pkg to use our mirror packages.appdevforall.org instead of packages.androide.com during app install.  
To test, do the ff. steps:
1) Uninstall the previous cogo app, if any, on phone
2) Install the new cogo app
3) After install and on app panel to create, open, etc. project, start the terminal
4) In terminal, type "pkg install zip", if it's working one can see that it's getting from packages.appdevforall.org from messages of pkg
> Fix for pkg to use our mirror packages.appdevforall.org instead of packages.androidide.com

- libs_source/androidsdk/android-sdk.zip
reduced the size of the apk by 2M by removing .DS_Store files from android-sdk.zip. these files are used by MacOS and are therefore unused by CoGo. gitignore can not be used here because it only filters files and directories, it does not inspect the contents of jars, zip files, etc.
> Removed DS_Store from android-sdk.zip

- app/src/main/res/layout/fragment_delete_project.xml
The layout of the delete project fragment has been improved by:
- Switching from `LinearLayout` to `FrameLayout` for the root layout.
- Using `layout_weight` for the RecyclerView to fill available space.
- Moving the no projects view, to be under the root `FrameLayout`, so that it can overlay the whole screen.
- Adjusting padding and alignment for better visual organization.
- Moving bottom buttons to their own layout.
- Updating the layout to make the `RecyclerView` take up the remaining space and improving the overall layout structure.
https://github.com/user-attachments/assets/60a2dc4a-225d-46ef-8c5e-a21fc460a5ec
[ADFA-696](https://appdevforall.atlassian.net/browse/ADFA-696)
[ADFA-696]: https://appdevforall.atlassian.net/browse/ADFA-696?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2Zh …
> Fix/adfa 696 | Improve delete project fragment layout

- libs_source/termux/v7/openjdk-17_17.0-30_arm.deb
- libs_source/termux/v8/openjdk-17_17.0-30_aarch64.deb
Demo folder refactored to only allocate a README file
This PR addresses issue ADFA-636 by removing the obsolete X11 Java demos from the `openjdk-17.0.deb` packages for both v7 (arm) and v8 (aarch64) architectures. This change significantly reduces the size of these packages, contributing to a smaller overall APK.
**Changes Made:**
* The `data.tar.xz` component within each `openjdk-17.0.deb` file was modified.
* The demo directory, previously located at `/data/data/com.itsaky.androidide/files/usr/opt/openjdk-17.0/demo` after installation, has been removed.
* A `README.txt` file has been added in place of the demos (at `/data/data/com.itsaky.androidide/files/usr/opt/openjdk-17.0/README.txt`). This file informs users that the demos were removed to save space.
* Ensured the repacked `.deb` …
> ADFA-636 | demo removed

- app/src/main/java/com/itsaky/androidide/fragments/TemplateDetailsFragment.kt
The `TemplateDetailsFragment` now directly opens the newly created project after successful creation, instead of first transitioning back to the main screen. This avoids a brief screen flash during the transition. The success message is flashed, and the project is added to recent projects before opening.
[Screen_recording_20250508_135122.webm](https://github.com/user-attachments/assets/a1ee8686-02c3-48ae-98ab-68c1e53c00df)
ADFA-675](https://appdevforall.atlassian.net/browse/ADFA-675)
> Fix/adfa 675 | Bug new Project creation

- .github/workflows/deploy-to-firestore-app-distribution.yml
Previously, the script could pick up the v7 APK due to directory order,
causing confusion or incorrect builds. This update filters for the v8
debug APK to align with our current deployment and testing targets.
> Ensure build script selects v8 APK variant explicitly, fix libjdwp error on CI

- .github/workflows/deploy-to-firestore-app-distribution.yml
Make the APK more discoverable with:
${{ github.repository }}
${{ github.sha }}
${{ github.ref }}
> ADFA-885 upgrading the fallback JIRA_URL for release notes in Firebase

- editor-treesitter/src/main/java/io/github/rosemoe/sora/editor/ts/TsAnalyzeWorker.kt
The solution avoids updateStyles() (heavy). Also, Avoids unnecessary recomputation and uses the safe Runnable hook on setStyles(...) to ensures CodeEditor.invalidate() happens at the right time, while also ensuring that the Styles object is properly marked as finalized before the invalidation occurs.
https://github.com/user-attachments/assets/d71cd073-ba92-4258-82a9-82503037ab72
[ADFA-550](https://appdevforall.atlassian.net/browse/ADFA-550)
[ADFA-550]: https://appdevforall.atlassian.net/browse/ADFA-550?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ADFA-550 |UI-refresh-breakpoints

- .github/workflows/deploy-to-firestore-app-distribution.yml
- app/build.gradle.kts
- app/src/main/java/com/itsaky/androidide/activities/OnboardingActivity.kt
- app/src/main/java/com/itsaky/androidide/activities/editor/BaseEditorActivity.kt
- composite-builds/build-deps-common/constants/src/main/java/org/adfa/constants/constants.kt
- composite-builds/build-logic/plugins/src/main/java/com/itsaky/androidide/plugins/tasks/CopyGradleCachesToAssetsTask.kt
- composite-builds/build-logic/plugins/src/main/java/com/itsaky/androidide/plugins/tasks/CopyGradleExecutableToAssetsTask.kt
- composite-builds/build-logic/plugins/src/main/java/com/itsaky/androidide/plugins/tasks/CopySdkToAssetsTask.kt
- gradle/libs.versions.toml
- libs_source/androidsdk/android-sdk.zip.br
- libs_source/gradle-8.7-bin.zip.br
- libs_source/gradle/localMvnRepository.zip.br
The local maven repo, android sdk and gradle bin blobs are now brotli compressed for full non-split asset builds, to achieve better compression.  Split asset builds still rely on the same assets-v?.zip for the usual zip files of three blobs mentioned above
> ADFA-927 brotli compression of local maven repo, android sdk and gradle bin blobs

- app/src/main/java/com/itsaky/androidide/activities/OnboardingActivity.kt
- app/src/main/java/com/itsaky/androidide/fragments/onboarding/IdeSetupConfigurationFragment.kt
- app/src/main/res/layout/layout_onboardng_setup_config.xml
- resources/src/main/res/values/strings.xml
Removes the "Auto-install" switch from the IDE setup configuration screen. The related logic that enabled/disabled other options based on this switch has also been removed.
The IDE setup process will now always proceed as if "Auto-install" was enabled, simplifying the user experience during onboarding.
[ADFA-873.webm](https://github.com/user-attachments/assets/5d3748b7-5384-4b18-8ebf-0b4112df61b3)
[ADFA-873](https://appdevforall.atlassian.net/browse/ADFA-873)
[ADFA-873]: https://appdevforall.atlassian.net/browse/ADFA-873?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ADFA-873: Removing manual setup option 

- app/build.gradle.kts
- app/src/main/java/com/itsaky/androidide/app/IDEApplication.kt
- app/src/main/java/com/itsaky/androidide/fragments/output/LogViewFragment.kt
- common/src/main/java/com/itsaky/androidide/utils/TestModeUtils.kt
Tree-sitter is a parsing library responsible for syntax highlighting and language analysis in the code editor.
Tests don't need syntax highlighting but the app tried to load Tree-sitter anyway, causing UnsatisfiedLinkError, this PR aims to fix this issue by disabling Tree-sitter during tests [unit and instrumentation]
See [this](https://appdevforall.atlassian.net/browse/ADFA-1157) for more details
> ADFA-1157: Fix TreeSitter native library loading during tests to prevent failures

- app/src/main/java/com/itsaky/androidide/ui/EditorBottomSheet.kt
- templates-api/src/main/java/com/itsaky/androidide/templates/base/models/Dependency.kt
- templates-api/src/main/java/com/itsaky/androidide/templates/base/modules/android/buildGradle.kt
- templates-api/src/main/java/com/itsaky/androidide/templates/base/util/AndroidManifestBuilder.kt
- templates-impl/src/main/assets/templates/tabbed/res/layout/activity_main.xml
- templates-impl/src/main/java/com/itsaky/androidide/templates/impl/tabbedActivity/srcActivity.kt
- templates-impl/src/main/java/com/itsaky/androidide/templates/impl/tabbedActivity/srcPagerAdapter.kt
- templates-impl/src/main/java/com/itsaky/androidide/templates/impl/tabbedActivity/tabbedActivityTemplate.kt
- ##### Warning: The Provider.forUseAtConfigurationTime method has been deprecated. This is scheduled to be removed in Gradle 9.0. 
| Template: All | Language: Kotlin | State: HIDDEN | Reason: The Provider.forUseAtConfigurationTime() method has been deprecated since Gradle 7.4 and is scheduled for removal in Gradle 9.0. This warning suggests that a plugin or internal build logic is using the method unnecessarily during the configuration phase. If this call is not found in the app's own codebase, the warning stems from a dependency or AndroidIDE’s internal Gradle logic and cannot be resolved at the application level. Therefore, it is technically safe to ignore | Documentation: https://docs.gradle.org/8.7/userguide/upgrading_version_7.html#for_use_at_configuration_time_deprecation
at …
> ADFA-1039 | Default internal app build warnings fix

- app/build.gradle.kts
- app/src/main/java/com/itsaky/androidide/activities/OnboardingActivity.kt
- common/src/main/java/com/itsaky/androidide/utils/Environment.java
- composite-builds/build-deps-common/constants/src/main/java/org/adfa/constants/constants.kt
- composite-builds/build-logic/plugins/src/main/java/com/itsaky/androidide/plugins/AndroidIDEAssetsPlugin.kt
- composite-builds/build-logic/plugins/src/main/java/com/itsaky/androidide/plugins/tasks/CopyGradleApiToAssetsTask.kt
- libs_source/gradle-api-8.7.jar.br
- libs_source/gradle-api-8.7.jar.zip
cache and copy back the generated gradle-api-8.7.jar during CoGo install for performance reasons
> ADFA-693 cache and copy back the generated gradle-api-8.7.jar

- editor/src/main/java/com/itsaky/androidide/editor/ui/EditorSearchLayout.kt
Request focus and show keyboard when EditorSearchLayout is shown
The `EditorSearchLayout` will now automatically request focus for the search input field and trigger the display of the soft keyboard when it becomes visible.
[ADFA-1088.webm](https://github.com/user-attachments/assets/924f7f30-b3a9-47b2-a7f2-0318b12950f0)
[ADFA-1088](https://appdevforall.atlassian.net/browse/ADFA-1088)
[ADFA-1088]: https://appdevforall.atlassian.net/browse/ADFA-1088?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ADFA-1088 | Autoplace cursor in input -Find in file- field and shpwing keyboard by default

- app/src/main/java/com/itsaky/androidide/ui/EditorBottomSheet.kt
Filtering out the following deprecated warnings:
The StartParameter.isConfigurationCacheRequested property has been deprecated. This is scheduled to be removed in Gradle 10.0. Please use 'configurationCache.requested' property on 'BuildFeatures' service instead. Consult the upgrading guide for further information: https://docs.gradle.org/8.14.3/userguide/upgrading_version_8.html#deprecated_startparameter_is_configuration_cache_requested
Retrieving attribute with a null key. This behavior has been deprecated. This will fail with an error in Gradle 10.0. Don't request attributes from attribute containers using null keys. Consult the upgrading guide for further information: https://docs.gradle.org/8.14.3/userguide/upgrading_version_8.html#null-attribute-lookup
> ADFA-1300 added deprecated warnings to filter out

- .github/workflows/debug.yml
Inspired by problem with ADFA-1321 and #290
> Protect COMMIT_MSG from shell interpretation of double-quote and other special characters

- resources/src/main/res/values/strings.xml
Replaces https://github.com/appdevforall/CodeOnTheGo/pull/379 because the other branch name was too long
> ADFA-1089 strings.xml - Change 'search' to 'find' so it matches other usage

- resources/src/main/res/values/strings.xml
Replaces https://github.com/appdevforall/CodeOnTheGo/pull/380 because branch name too long and also merge conflicts
> ADFA-1096 strings.xml - Add plural form of project to delete msg

- app/src/main/java/com/itsaky/androidide/actions/filetree/HelpAction.kt
- idetooltips/src/main/java/com/itsaky/androidide/idetooltips/TooltipTag.kt
Show tooltip when `Help` is clicked from file action.
[Jira ticket](https://appdevforall.atlassian.net/browse/ADFA-1580)
https://github.com/user-attachments/assets/2c6128e3-0e83-4be9-a75a-69646e465c58
> fix(ADFA-1580): Show tooltip for file tree help

- idetooltips/src/main/java/com/itsaky/androidide/idetooltips/ToolTipManager.kt
LastChange was updated to have multiple entries corresponding to different subsets of the content. New database is at https://drive.google.com/drive/u/0/folders/1uyo2M8hMLZT4WYYQmPglfeoGNqOMLVyS
Ticket [https://appdevforall.atlassian.net/browse/ADFA-1550](https://appdevforall.atlassian.net/browse/ADFA-1550) "Track date of update for documentation.db and for the individual content sets shoved into it"
--
New schema is:
CREATE TABLE LastChange (
documentationSet TEXT,
changeTime TIMESTAMP,
who TEXT
);
--
This breaks tooltips because the static LastChange query in ToolTipManager doesn't grab the correct data. Fixing column names and adding a where clause to find the full-database-change record fixes this issue,
> Change the 'last change' tooltip query to work with new documentation database

- resources/src/main/res/values/strings.xml
Changed "Learn about Code on the Go here" to direct the user to the quick start instead. There's another ticket to make that entire section clickable and point at the Quick Start page.
> ADFA-1675-Main-page-change-learn-msg-to-quickstart

- app/src/main/res/layout/content_editor.xml
This PR adds horizontal padding to the `TextView` that is displayed on the project page when no files are open. Following a recent update where the list formatting was removed, the text ran to the edges of the screen. This change introduces a `16dp` padding on the left and right sides to improve the layout and visual appearance.
The change is purely visual. Here's how it looks **before** and **after**:
<p align="center">
</p>
[ADFA-1698](https://appdevforall.atlassian.net/browse/ADFA-1698)
This is a minor, isolated UI fix that only affects the `no_editor_summary` TextView. It has no impact on app logic or functionality.
[ADFA-1698]: https://appdevforall.atlassian.net/browse/ADFA-1698?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ADFA-1698 | Add horizontal padding to the no-editor summary text

- resources/src/main/res/values/strings.xml
Fixed comma splice in message displayed when you
1. open saved project
2. choose to use a folder that doesn't have an Android project in it.
Note - I have to record a video to be able to read the message because it disappears so quickly
> ADFA-1728-Fix-grammar-nonvalid-folder-msg

- assets/release/common/data/common/localMvnRepository.zip.br
recompress koltlin-compiler-embeddable jar 1.9.22 and kotlin-stdlib jars versions 1.9.22 and 2.0.21
> recompress koltlin-compiler-embeddable jar 1.9.22 
