appdevforall/CodeOnTheGo

app/build.gradle.kts, app/src/androidTest/kotlin/com/itsaky/androidide/CleanupTest.kt, app/src/androidTest/kotlin/com/itsaky/androidide/OrderedTestSuite.kt, app/src/androidTest/kotlin/com/itsaky/androidide/PermissionsScreenTest.kt, app/src/androidTest/kotlin/com/itsaky/androidide/ProjectBuildTestWithGroovyGradle.kt, app/src/androidTest/kotlin/com/itsaky/androidide/ProjectBuildTestWithKtsGradle.kt, app/src/androidTest/kotlin/com/itsaky/androidide/WelcomeScreenTest.kt, app/src/androidTest/kotlin/com/itsaky/androidide/helper/ProjectBuildHelper.kt, app/src/androidTest/kotlin/com/itsaky/androidide/scenarios/InitializationProjectAndCancelingBuildScenario.kt, app/src/androidTest/kotlin/com/itsaky/androidide/scenarios/NavigateToMainScreenScenario.kt, app/src/androidTest/kotlin/com/itsaky/androidide/screens/ProjectSettingsScreen.kt
Allow tests to be executable in one scope
=> ADFA-365 - Permission Screen Test

app/src/main/java/com/itsaky/androidide/actions/EditorActivityAction.kt, editor/src/main/assets/editor/schemes/default/default.json, resources/src/main/res/values/theme_blue_wave.xml
Fix blue wave light theme popup menu background color
1.JSON Syntax Highlighting:** Modifies `EditorActivityAction.kt` to ensure proper JSON syntax highlighting within the editor. (Related to search results 2 and 3 about JSON syntax highlighting in Splunk)
2.  **Surface Color:** Updates the default theme's JSON file (`default.json`) to set the `surface` color to `#ffffff` (white).
[ADFA-476](https://appdevforall.atlassian.net/browse/ADFA-476)
[ADFA-476]: https://appdevforall.atlassian.net/browse/ADFA-476?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ADFA - 476 | Update background colors

app/src/main/AndroidManifest.xml
The `configChanges` attribute for `EditorActivityKt` in `AndroidManifest.xml` is updated to include `uiMode`, allowing the activity to handle changes in the user interface mode (like dark mode) without being recreated.
[ADFA-433](https://appdevforall.atlassian.net/browse/ADFA-433)
[ADFA-433]: https://appdevforall.atlassian.net/browse/ADFA-433?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ADFA-433 | Update configChanges in AndroidManifest.xml

app/src/main/java/com/itsaky/androidide/activities/OnboardingActivity.kt, app/src/main/java/com/itsaky/androidide/utils/TemplateRecipeExecutor.kt, common/src/main/java/com/itsaky/androidide/managers/ToolsManager.java, common/src/main/java/com/itsaky/androidide/utils/Environment.java, composite-builds/build-logic/plugins/src/main/java/com/itsaky/androidide/plugins/AndroidIDEAssetsPlugin.kt, composite-builds/build-logic/plugins/src/main/java/com/itsaky/androidide/plugins/TerminalBootstrapPackagesPlugin.kt, composite-builds/build-logic/plugins/src/main/java/com/itsaky/androidide/plugins/tasks/CopyGradleCachesToAssetsTask.kt, composite-builds/build-logic/plugins/src/main/java/com/itsaky/androidide/plugins/tasks/CopyGradleExecutableToAssetsTask.kt, composite-builds/build-logic/plugins/src/main/java/com/itsaky/androidide/plugins/tasks/CopyPlatformToolsToAssetsTask.kt, composite-builds/build-logic/plugins/src/main/java/com/itsaky/androidide/plugins/tasks/CopyUsrFolderToAssetsTask.kt, composite-builds/build-logic/plugins/src/main/java/com/itsaky/androidide/plugins/tasks/GradleWrapperGeneratorTask.kt, constants/src/main/java/com/adfa/constants/constants.kt, gradle.properties, templates-api/src/main/java/com/itsaky/androidide/templates/RecipeExecutor.kt, templates-api/src/main/java/com/itsaky/androidide/templates/base/ProjectTemplateBuilder.kt, templates-api/src/main/java/com/itsaky/androidide/templates/base/base.kt, templates-api/src/main/java/com/itsaky/androidide/templates/base/root/gradleWrapperSrc.kt, templates-api/src/main/java/com/itsaky/androidide/templates/base/root/settings.kt
Single copy of gradle-<version>-bin.zip across projects, and type fixes for com.adfa.constants
=> ADFA-408 Simplify gradle on the phone 

app/build.gradle.kts, composite-builds/build-logic/plugins/src/main/java/com/itsaky/androidide/plugins/conf/AndroidModuleConf.kt
Only allow armeabi-v7a and arm64-v8a and also exclude com.sun.jna from apk
=> Eliminate x86 and x86_64 related binaries

app/src/main/java/com/itsaky/androidide/utils/TooltipUtils.kt, app/src/main/res/layout/ide_tooltip_window.xml
- Update layout editor version.
- Refactor TooltipUtils to enhance tooltip display logic.
- Modify the IDE tooltip layout to use a TextView for "See More" and remove unused buttons.
- Update tooltip html styles.
- Modify tooltip to have hyperlinks.
https://github.com/user-attachments/assets/e4f71829-3ff0-4649-9cc6-32af4d1f7789
[ADFA-295](https://appdevforall.atlassian.net/browse/ADFA-295)
[ADFA-295]: https://appdevforall.atlassian.net/browse/ADFA-295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ADFA - 295 | Refactor: Update TooltipUtils and IDE tooltip layout

.github/workflows/deploy-to-firestore-app-distribution.yml, composite-builds/build-logic/plugins/build.gradle.kts, composite-builds/build-logic/plugins/src/main/java/com/itsaky/androidide/plugins/ExternalAssetsPlugin.kt, composite-builds/build-logic/plugins/src/main/java/com/itsaky/androidide/plugins/extension/ExternalAssetsExtension.kt, composite-builds/build-logic/plugins/src/main/java/com/itsaky/androidide/plugins/tasks/AddExternalAssetTask.kt, composite-builds/build-logic/plugins/src/main/java/com/itsaky/androidide/plugins/tasks/SetupAapt2Task.kt, composite-builds/build-logic/plugins/src/main/java/com/itsaky/androidide/plugins/util/DownloadUtils.kt, composite-builds/build-logic/plugins/src/main/java/com/itsaky/androidide/plugins/util/Misc.kt, gradle.properties, subprojects/libjdwp/build.gradle.kts
This PR aims to externalize builds for `oj-libjdwp`. See [ADFA-869](https://appdevforall.atlassian.net/browse/ADFA-869) for more details.
[ADFA-869]: https://appdevforall.atlassian.net/browse/ADFA-869?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ADFA-869: externalize libjdwp build

app/src/main/java/com/itsaky/androidide/activities/editor/BaseEditorActivity.kt
https://appdevforall.atlassian.net/browse/ADFA-506
Please take a look at this PR as well:
https://github.com/appdevforall/layouteditor/pull/8
=> ADFA-506: refactor(BaseEditorActivity): remove unnecessary file close call in UI designer result handling

app/src/main/java/com/itsaky/androidide/adapters/MainActionsListAdapter.kt
https://appdevforall.atlassian.net/browse/ADFA-1049
=> ADFA-1049:  Remove capitalizeWords() from MainActionsListAdapter.kt

composite-builds/build-logic/plugins/src/main/java/com/itsaky/androidide/plugins/tasks/AddBrotliFileToAssetsTask.kt
Additionally set brotli compression to level 11 and window to 24  for tooling-api-all.jar
=> set brotli compression to level 11 and window to 24 for tooling jar

preferences/src/main/java/com/itsaky/androidide/preferences/internal/BuildPreferences.kt, subprojects/builder-model-impl/src/main/java/com/android/build/gradle/options/BooleanOption.kt
enable build-cache and disable info in gradle flags
=> ADFA-261 enable build-cache and disable info in gradle flags

app/src/main/java/com/itsaky/androidide/activities/OnboardingActivity.kt, preferences/src/main/java/com/itsaky/androidide/preferences/internal/BuildPreferences.kt, subprojects/tooling-api-impl/src/main/java/com/itsaky/androidide/tooling/impl/ToolingApiServerImpl.kt
Simplify gradle-8.7-bin.zip extraction, i.e. duplication for each new project
=> ADFA-687 Simplify gradle-8.7-bin.zip extraction

layouteditor
Remove conflicting 'layouteditor' symlink
=> fix(ADFA-1185): Remove symlink

app/src/release/assets/data/common/gradle-8.14.3-bin.zip.br, common/build.gradle.kts, common/src/main/java/com/itsaky/androidide/managers/ToolsManager.java
re-brotli localMvnRepository.zip.br and gradle-8.14.3-bin.zip.br and tooling-api-all.jar.br extraction
=> ADFA-1264 re-brotli gradle-8.14.3-bin.zip.br and tooling-api-all.jar.br extraction

app/src/main/java/com/itsaky/androidide/assets/SplitAssetsInstaller.kt
Extracting and installing zips directly from assets zip to reduce debug apk install time.
=> ADFA-1330 extract and install zips directly from assets zip

app/src/main/java/com/itsaky/androidide/localWebServer/WebServer.kt
Remove LIMIT 1 from LocalWebServer query for content
Better error checking and reporting for same
=> ADFA-1336 Fix sqlite query for LocalWebServer content

fastlane/README.md
See [ADFA-1313](https://appdevforall.atlassian.net/browse/ADFA-1313) for more details.
[ADFA-1313]: https://appdevforall.atlassian.net/browse/ADFA-1313?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ADFA-1313: add README for fastlane directory

app/src/main/java/com/itsaky/androidide/localWebServer/WebServer.kt, idetooltips/src/main/java/com/itsaky/androidide/idetooltips/ToolTipManager.kt
Update the queries to handle both cases
Adjust the Brotli compression behavior in the web server
New debug enable mechanism
Code written by David Schachter
=> ADFA-1399 support searching android tooltips in java and kotlin files

app/src/main/java/com/itsaky/androidide/actions/file/ShowTooltipAction.kt, app/src/main/java/com/itsaky/androidide/fragments/IDEPreferencesFragment.kt, app/src/main/java/com/itsaky/androidide/fragments/MainFragment.kt, editor/src/main/java/com/itsaky/androidide/editor/ui/EditorActionsMenu.kt, editor/src/main/java/com/itsaky/androidide/editor/ui/EditorCompletionWindow.kt, idetooltips/src/main/java/com/itsaky/androidide/idetooltips/IDETooltipItem.kt, idetooltips/src/main/java/com/itsaky/androidide/idetooltips/ToolTipManager.kt
Extend the tooltip "i" info button with more info
=> ADFA-1385 display the category rowid and lastchange

app/build.gradle.kts
disable recompression of apk in debug builds
=> ADFA-1462 disable recompression of apk in debug builds

.github/workflows/debug.yml
=> ADFA-1481 Remove step for git submodule from debug.yml

app/src/main/java/com/itsaky/androidide/app/configuration/IDEBuildConfigProviderImpl.kt, app/src/test/java/com/itsaky/androidide/app/configuration/IDEBuildConfigProviderImplTest.kt, common/src/main/java/com/itsaky/androidide/managers/ToolsManager.java, composite-builds/build-logic/plugins/src/main/java/com/itsaky/androidide/plugins/conf/AndroidModuleConf.kt
=> ADFA-674 remove x86 support code

app/build.gradle.kts, app/src/test/java/com/itsaky/androidide/app/configuration/IDEBuildConfigProviderImplTest.kt
Added v2 and v3 signing to both debug and release apks
=> ADFA-1511 enable v2 v3 signing

resources/src/main/res/values/strings.xml
Lower-case p to be consistent with Google Material guidelines
=> Update strings.xml - fixed Recent projects capitalization

common/src/main/java/com/itsaky/androidide/utils/ViewExtensions.kt, layouteditor/src/main/java/org/appdevforall/codeonthego/layouteditor/editor/DesignEditor.kt
Set tooltips on views in xml preview
[Jira ticket](https://appdevforall.atlassian.net/browse/ADFA-1484)
https://github.com/user-attachments/assets/873b5081-1992-42cd-97bf-71a748292f99
=> ADFA-1484: Tooltips on layout editor views

resources/src/main/res/values/strings.xml
=> ADFA-835 - update "show non-printing characters" pref

resources/src/main/res/values/strings.xml
Change "delete tab..." pref and description to describe the feature
=> ADFA-842-Smart-backspace-indent-pref

resources/src/main/res/values/strings.xml
=> Prefs: Editor/font size 

resources/src/main/res/values/strings.xml
The content on the project page is updated. Various typos and style inconsistencies are fixed.
=> ADFA-1693-Update-multiple-messages-in-strings.xml
